# Generated by Django 5.1.7 on 2025-03-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='categorie',
            field=models.CharField(choices=[('financier', 'Financier'), ('operationnel', 'Opérationnel'), ('autre', 'Autre')], default='autre', max_length=50),
        ),
    ]
