# Generated by Django 5.1.7 on 2025-03-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0002_kpi_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='date',
            field=models.DateField(),
        ),
    ]
