# Generated by Django 5.1.7 on 2025-03-30 23:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0003_alter_kpi_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentaire',
            options={'ordering': ['-date_creation']},
        ),
        migrations.AlterModelOptions(
            name='kpi',
            options={'ordering': ['-date', 'nom'], 'verbose_name': 'KPI', 'verbose_name_plural': 'KPIs'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
        migrations.AddField(
            model_name='commentaire',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='is_insight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kpi',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='kpi',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='seuil_critique',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='kpi',
            name='seuil_warning',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='kpi',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='PowerBIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('fichier', models.FileField(upload_to='powerbi_reports/')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_upload'],
            },
        ),
    ]
