# Generated by Django 5.1.7 on 2025-03-31 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0004_alter_commentaire_options_alter_kpi_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Analyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('chart_type', models.CharField(choices=[('line', 'Ligne'), ('bar', 'Barres'), ('pie', 'Camembert')], max_length=20)),
                ('categorie', models.CharField(choices=[('financier', 'Financier'), ('operationnel', 'Opérationnel'), ('autre', 'Autre')], default='autre', max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
                ('plotly_config', models.JSONField(blank=True, null=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kpis', models.ManyToManyField(to='pilot.kpi')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
